<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DevBR.Discovery</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevBR.Application\DevBR.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
